feat adding metadata to files
eduNEXT/xblock-filesmanager pull request #38
Opened 2024-03-01 16:33 UTC by johnvente

**Merge checklist:**
Check off if complete *or* not applicable:
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Fixup commits are squashed away
- [ ] Unit tests added/updated
- [ ] Manual testing instructions provided
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

2024-03-06 16:06 UTC, BryanttV requested changes

2024-03-06 16:06 UTC, BryanttV commented on react-app/components/FileManager/index.jsx
Hi @johnvente, the implementation works great, I just have a few comments:

1. In the handler response the files are returned anyway, aren't we going to remove them from there too?
2. With the date picker it is not possible to configure by days, is there a way to do it including a time? or is not required this option?
3. We should update the instructions and documentation including the new date functionality.
4. Is it possible to set dates also for folders? If it is not possible, I think that the option should not appear when selecting a folder.

Additionally,

1. When I try to download several files (including folders) I get an error message, but it still generates the zip to download.
![image](https://github.com/eduNEXT/xblock-filesmanager/assets/64033729/98907e65-4f47-4954-9745-0a2bce98b301)

2024-03-06 17:28 UTC, johnvente commented on react-app/components/FileManager/constants.js
Good idean, thanks

2024-03-06 18:28 UTC, johnvente commented on react-app/components/FileManager/index.jsx
Hi there @BryanttV 
1. I suggested that to feliple but he said that wouldn't be neccessary
2. It's not required the time, at least for now
3. I will add the instructions and the documentation for this
4. It's possible to do it for folders but it seems like a backend error isn't saving the metadata of those one

2024-03-06 20:56 UTC, johnvente commented
Hi @BryanttV I've solved the problem with the folders and I added the instructions could you check again please?

2024-03-07 13:01 UTC, BryanttV commented
Hi @johnvente, thanks. LGTM!

2024-03-07 13:02 UTC, BryanttV approved these changes

2024-03-07 13:23 UTC, johnvente commented
> Just one thing, could we update the cover letter with the new changes?

Thanks, done!

2024-03-07 15:05 UTC, merged